### ISSUE TITLE
can I ask about the segmentation groundtruth of brazilian coffee dataset?

### ISSUE THREAD

**Issue by 999Yy999** [matheusbarrosp/sr-semseg-end2end#1]
I download the coffee dataset from the website http://patreo.dcc.ufmg.br/2017/11/12/brazilian-coffee-scenes-dataset/, but it doesn't have segmentation label, only has classification label. Could you please tell me how to get the scene segmentation label? Thanks a lot!!!!!!!!!!!!!!

**Comment by matheusbarrosp** [comment]
Hello. The semantic segmentation version of the dataset is not currently available on the website. Please send me an email at [matheusbarrosp@gmail.com](mailto:matheusbarrosp@gmail.com) so I can link you the semantic segmentation dataset directly. Thank you for reaching out :)
